# Generated by Django 4.1 on 2024-05-10 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backtester", "0002_strategy_strategydetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=100)),
                ("exchange", models.CharField(max_length=100)),
                ("currency", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="strategy",
            name="instrument",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backtester.instrument",
            ),
        ),
    ]
