# Generated by Django 4.1 on 2024-05-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backtester", "0003_instrument_strategy_instrument"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="description",
            field=models.TextField(default="No description provided."),
        ),
    ]
